# Generated by Django 5.0.2 on 2024-03-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category1_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_image', models.ImageField(upload_to='Category2_Products_images/')),
                ('Product_Desc', models.TextField()),
                ('Is_Catogry', models.BooleanField(default=False)),
                ('Main_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes', to='products.category1')),
            ],
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_image', models.ImageField(upload_to='Category3_Products_images/')),
                ('Product_Desc', models.TextField()),
                ('category2_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes2', to='products.category2')),
            ],
        ),
        migrations.CreateModel(
            name='Category3_coverIamge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Category3_cover_images/')),
                ('category3_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categoryes3', to='products.category2')),
            ],
        ),
    ]
