# Generated by Django 5.0.2 on 2024-04-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category3_coveriamge_category3_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_image', models.ImageField(upload_to='main_images/')),
                ('cover_image', models.ImageField(upload_to='category_covers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='category2',
            name='Main_category_fk',
        ),
        migrations.RemoveField(
            model_name='final_product',
            name='category2_fk',
        ),
        migrations.RemoveField(
            model_name='category3',
            name='category2_fk',
        ),
        migrations.RemoveField(
            model_name='category3_coveriamge',
            name='category3_fk',
        ),
        migrations.RemoveField(
            model_name='final_product_for_c3',
            name='category2_fk',
        ),
        migrations.RemoveField(
            model_name='weights_for_c3',
            name='category3_fk',
        ),
        migrations.RemoveField(
            model_name='grinding_for_c3',
            name='category3_fk',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_category', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=15)),
                ('grinding_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.subproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='Benefits_for_C3',
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Final_Product',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3_coverIamge',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
        migrations.DeleteModel(
            name='Weights_for_C3',
        ),
        migrations.DeleteModel(
            name='Final_Product_For_C3',
        ),
        migrations.DeleteModel(
            name='grinding_for_C3',
        ),
    ]
