# Generated by Django 5.0.4 on 2024-05-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startups', '0002_startup_model_startup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_model',
            name='country_id',
            field=models.CharField(choices=[('AF', 'Afghanistan')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
