# Generated by Django 5.0.2 on 2024-03-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level_1_const',
            fields=[
                ('sound', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('word 1', models.CharField(blank=True, max_length=40, verbose_name='Word 1')),
                ('word 2', models.CharField(blank=True, max_length=40, verbose_name='Word 2')),
                ('word 3', models.CharField(blank=True, max_length=40, verbose_name='Word 3')),
                ('word 4', models.CharField(blank=True, max_length=40, verbose_name='Word 4')),
                ('word 5', models.CharField(blank=True, max_length=40, verbose_name='Word 5')),
                ('word 6', models.CharField(blank=True, max_length=40, verbose_name='Word 6')),
                ('word 7', models.CharField(blank=True, max_length=40, verbose_name='Word 7')),
                ('word 8', models.CharField(blank=True, max_length=40, verbose_name='Word 8')),
                ('word 9', models.CharField(blank=True, max_length=40, verbose_name='Word 9')),
                ('word 10', models.CharField(blank=True, max_length=40, verbose_name='Word 10')),
                ('word 11', models.CharField(blank=True, max_length=40, verbose_name='Word 11')),
                ('word 12', models.CharField(blank=True, max_length=40, verbose_name='Word 12')),
                ('word 13', models.CharField(blank=True, max_length=40, verbose_name='Word 13')),
                ('word 14', models.CharField(blank=True, max_length=40, verbose_name='Word 14')),
                ('word 15', models.CharField(blank=True, max_length=40, verbose_name='Word 15')),
                ('word 16', models.CharField(blank=True, max_length=40, verbose_name='Word 16')),
                ('word 17', models.CharField(blank=True, max_length=40, verbose_name='Word 17')),
                ('word 18', models.CharField(blank=True, max_length=40, verbose_name='Word 18')),
                ('word 19', models.CharField(blank=True, max_length=40, verbose_name='Word 19')),
                ('word 20', models.CharField(blank=True, max_length=40, verbose_name='Word 20')),
            ],
        ),
        migrations.CreateModel(
            name='Level_2_v_d',
            fields=[
                ('sound_id', models.AutoField(primary_key=True, serialize=False)),
                ('sound', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('word 1', models.CharField(blank=True, max_length=40, verbose_name='Word 1')),
                ('word 2', models.CharField(blank=True, max_length=40, verbose_name='Word 2')),
                ('word 3', models.CharField(blank=True, max_length=40, verbose_name='Word 3')),
                ('word 4', models.CharField(blank=True, max_length=40, verbose_name='Word 4')),
                ('word 5', models.CharField(blank=True, max_length=40, verbose_name='Word 5')),
                ('word 6', models.CharField(blank=True, max_length=40, verbose_name='Word 6')),
                ('word 7', models.CharField(blank=True, max_length=40, verbose_name='Word 7')),
                ('word 8', models.CharField(blank=True, max_length=40, verbose_name='Word 8')),
                ('word 9', models.CharField(blank=True, max_length=40, verbose_name='Word 9')),
                ('word 10', models.CharField(blank=True, max_length=40, verbose_name='Word 10')),
                ('word 11', models.CharField(blank=True, max_length=40, verbose_name='Word 11')),
                ('word 12', models.CharField(blank=True, max_length=40, verbose_name='Word 12')),
                ('word 13', models.CharField(blank=True, max_length=40, verbose_name='Word 13')),
                ('word 14', models.CharField(blank=True, max_length=40, verbose_name='Word 14')),
                ('word 15', models.CharField(blank=True, max_length=40, verbose_name='Word 15')),
                ('word 16', models.CharField(blank=True, max_length=40, verbose_name='Word 16')),
                ('word 17', models.CharField(blank=True, max_length=40, verbose_name='Word 17')),
                ('word 18', models.CharField(blank=True, max_length=40, verbose_name='Word 18')),
                ('word 19', models.CharField(blank=True, max_length=40, verbose_name='Word 19')),
                ('word 20', models.CharField(blank=True, max_length=40, verbose_name='Word 20')),
            ],
        ),
        migrations.CreateModel(
            name='Level_3_sent',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
