# Generated by Django 5.0.2 on 2024-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('words_sents', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='level_3_sent',
            name='sentence',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
