# Generated by Django 5.0.2 on 2024-03-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_readingtest_alter_level_3_sent_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingtest',
            old_name='words_sents',
            new_name='words_and_sents',
        ),
    ]
