# Generated by Django 5.0.2 on 2024-04-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_lvl_1_sd_lvl_2_sd_lvl_3_sd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lvl_1_sd',
        ),
        migrations.DeleteModel(
            name='lvl_2_sd',
        ),
        migrations.DeleteModel(
            name='lvl_3_sd',
        ),
    ]
