# Generated by Django 2.2.7 on 2023-08-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(verbose_name='سعر الكشف : '),
        ),
    ]
