# Generated by Django 2.2.7 on 2023-08-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230830_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='profile', verbose_name='الصوره الشخصيه'),
            preserve_default=False,
        ),
    ]
