# Generated by Django 3.2.8 on 2023-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='محافظتك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوانك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تخصصك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نبذه عنك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wating_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد ساعات عملك '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ألاسم : '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='منا انا : '),
        ),
    ]
