# Generated by Django 3.2.8 on 2023-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230831_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب جوجل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب الفيس'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب تويتر'),
        ),
    ]
