# Generated by Django 3.2.7 on 2023-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230901_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jous_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='محافظتك'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default=1, max_length=50, verbose_name='عنوانك'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='ألاسم : '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(max_length=50, verbose_name='نبذه عنك'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(max_length=50, verbose_name='عدد ساعات عملك '),
        ),
    ]
