# Generated by Django 5.0.2 on 2024-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='Catogry_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
