# Generated by Django 5.0.2 on 2024-03-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category1_catogry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category1',
            name='Catogry_name',
        ),
    ]
