# Generated by Django 5.0.2 on 2024-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category1_catogry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category1',
            name='Cover_image',
            field=models.ImageField(default=1, upload_to='Category1_cover_images/'),
            preserve_default=False,
        ),
    ]
