# Generated by Django 5.0.2 on 2024-04-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category2_category3_category3_coveriamge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='Product_Desc',
        ),
        migrations.RemoveField(
            model_name='category3',
            name='Product_Desc',
        ),
        migrations.AlterField(
            model_name='category2',
            name='Main_category_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes', to='products.category1', verbose_name='Category 1 Name'),
        ),
        migrations.AlterField(
            model_name='category3',
            name='category2_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes2', to='products.category2', verbose_name='Category 2 Name'),
        ),
        migrations.CreateModel(
            name='Benefits_for_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Benefit', models.CharField(max_length=255)),
                ('category3_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Benefits_for_Category3', to='products.category3')),
            ],
        ),
        migrations.CreateModel(
            name='grinding_for_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grinding_Type', models.CharField(max_length=50)),
                ('category3_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grinding_for_Category3', to='products.category3')),
            ],
        ),
        migrations.CreateModel(
            name='Weights_for_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.CharField(max_length=15)),
                ('category3_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Weights_for_Category3', to='products.category3')),
            ],
        ),
    ]
