# Generated by Django 5.0.2 on 2024-04-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category2_product_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category3_coveriamge',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories3', to='products.category2'),
        ),
        migrations.CreateModel(
            name='Final_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_image', models.ImageField(upload_to='Category3_Products_images/')),
                ('category2_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories2', to='products.category2', verbose_name='Category 2 Name')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Product_For_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_image', models.ImageField(upload_to='Category3_Products_images/')),
                ('category2_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes31', to='products.category3', verbose_name='Category 3 Name')),
            ],
        ),
        migrations.AlterField(
            model_name='benefits_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Benefits_for_Final_Product_For_C3', to='products.final_product_for_c3'),
        ),
        migrations.AlterField(
            model_name='grinding_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grinding_for_Final_Product_For_C3', to='products.final_product_for_c3'),
        ),
        migrations.AlterField(
            model_name='weights_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Weights_for_Final_Product_For_C3', to='products.final_product_for_c3'),
        ),
    ]
