# Generated by Django 5.0.2 on 2024-04-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category1_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_product_for_c3',
            name='category2_fk',
        ),
        migrations.AddField(
            model_name='category2',
            name='Cover_image',
            field=models.ImageField(default=1, upload_to='Category3_cover_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='final_product',
            name='category2_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories2', to='products.category1', verbose_name='Category 2 Name'),
        ),
        migrations.CreateModel(
            name='Final_Product_For_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_image', models.ImageField(upload_to='Category3_Products_images/')),
                ('category2_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryes31', to='products.category2', verbose_name='Category 2 Name')),
            ],
        ),
        migrations.AlterField(
            model_name='benefits_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Benefits_for_Final_Product_For_C2', to='products.final_product_for_c2'),
        ),
        migrations.AlterField(
            model_name='grinding_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grinding_for_Final_Product_For_C2', to='products.final_product_for_c2'),
        ),
        migrations.AlterField(
            model_name='weights_for_c3',
            name='category3_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Weights_for_Final_Product_For_C2', to='products.final_product_for_c2'),
        ),
        migrations.DeleteModel(
            name='Category3_coverIamge',
        ),
        migrations.DeleteModel(
            name='Final_Product_For_C3',
        ),
    ]
