# Generated by Django 5.0.2 on 2024-04-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_final_product_for_c3_category2_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='Is_Catogry',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
    ]
