# Generated by Django 4.2.4 on 2023-09-08 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_producttable_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 16, 32, 50, 470582), verbose_name='publish date'),
        ),
    ]
