# Generated by Django 5.0.2 on 2024-04-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Sponsors_logos/')),
                ('phone_number', models.CharField(max_length=20)),
                ('work_fields', models.CharField(max_length=100)),
            ],
        ),
    ]
